/*
 * This file is generated by jOOQ.
 */
package schema.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import schema.Indexes;
import schema.Keys;
import schema.Webapp;
import schema.tables.records.ApartmentRoomRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApartmentRoom extends TableImpl<ApartmentRoomRecord> {

    private static final long serialVersionUID = 1674571330;

    /**
     * The reference instance of <code>webapp.apartment_room</code>
     */
    public static final ApartmentRoom APARTMENT_ROOM = new ApartmentRoom();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApartmentRoomRecord> getRecordType() {
        return ApartmentRoomRecord.class;
    }

    /**
     * The column <code>webapp.apartment_room.apartment_id</code>.
     */
    public final TableField<ApartmentRoomRecord, Integer> APARTMENT_ID = createField(DSL.name("apartment_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>webapp.apartment_room.room_id</code>.
     */
    public final TableField<ApartmentRoomRecord, Integer> ROOM_ID = createField(DSL.name("room_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>webapp.apartment_room</code> table reference
     */
    public ApartmentRoom() {
        this(DSL.name("apartment_room"), null);
    }

    /**
     * Create an aliased <code>webapp.apartment_room</code> table reference
     */
    public ApartmentRoom(String alias) {
        this(DSL.name(alias), APARTMENT_ROOM);
    }

    /**
     * Create an aliased <code>webapp.apartment_room</code> table reference
     */
    public ApartmentRoom(Name alias) {
        this(alias, APARTMENT_ROOM);
    }

    private ApartmentRoom(Name alias, Table<ApartmentRoomRecord> aliased) {
        this(alias, aliased, null);
    }

    private ApartmentRoom(Name alias, Table<ApartmentRoomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ApartmentRoom(Table<O> child, ForeignKey<O, ApartmentRoomRecord> key) {
        super(child, key, APARTMENT_ROOM);
    }

    @Override
    public Schema getSchema() {
        return Webapp.WEBAPP;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.APARTMENT_ROOM_PRIMARY, Indexes.APARTMENT_ROOM_ROOM_ID);
    }

    @Override
    public UniqueKey<ApartmentRoomRecord> getPrimaryKey() {
        return Keys.KEY_APARTMENT_ROOM_PRIMARY;
    }

    @Override
    public List<UniqueKey<ApartmentRoomRecord>> getKeys() {
        return Arrays.<UniqueKey<ApartmentRoomRecord>>asList(Keys.KEY_APARTMENT_ROOM_PRIMARY);
    }

    @Override
    public List<ForeignKey<ApartmentRoomRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ApartmentRoomRecord, ?>>asList(Keys.APARTMENT_ROOM_IBFK_1, Keys.APARTMENT_ROOM_IBFK_2);
    }

    public Apartment apartment() {
        return new Apartment(this, Keys.APARTMENT_ROOM_IBFK_1);
    }

    public Room room() {
        return new Room(this, Keys.APARTMENT_ROOM_IBFK_2);
    }

    @Override
    public ApartmentRoom as(String alias) {
        return new ApartmentRoom(DSL.name(alias), this);
    }

    @Override
    public ApartmentRoom as(Name alias) {
        return new ApartmentRoom(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApartmentRoom rename(String name) {
        return new ApartmentRoom(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApartmentRoom rename(Name name) {
        return new ApartmentRoom(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
