/*
 * This file is generated by jOOQ.
 */
package schema.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import schema.Indexes;
import schema.Keys;
import schema.Webapp;
import schema.tables.records.FacilitiesProblemRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FacilitiesProblem extends TableImpl<FacilitiesProblemRecord> {

    private static final long serialVersionUID = -341732998;

    /**
     * The reference instance of <code>webapp.facilities_problem</code>
     */
    public static final FacilitiesProblem FACILITIES_PROBLEM = new FacilitiesProblem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FacilitiesProblemRecord> getRecordType() {
        return FacilitiesProblemRecord.class;
    }

    /**
     * The column <code>webapp.facilities_problem.facilities_id</code>.
     */
    public final TableField<FacilitiesProblemRecord, Integer> FACILITIES_ID = createField(DSL.name("facilities_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>webapp.facilities_problem.problem_id</code>.
     */
    public final TableField<FacilitiesProblemRecord, Integer> PROBLEM_ID = createField(DSL.name("problem_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>webapp.facilities_problem</code> table reference
     */
    public FacilitiesProblem() {
        this(DSL.name("facilities_problem"), null);
    }

    /**
     * Create an aliased <code>webapp.facilities_problem</code> table reference
     */
    public FacilitiesProblem(String alias) {
        this(DSL.name(alias), FACILITIES_PROBLEM);
    }

    /**
     * Create an aliased <code>webapp.facilities_problem</code> table reference
     */
    public FacilitiesProblem(Name alias) {
        this(alias, FACILITIES_PROBLEM);
    }

    private FacilitiesProblem(Name alias, Table<FacilitiesProblemRecord> aliased) {
        this(alias, aliased, null);
    }

    private FacilitiesProblem(Name alias, Table<FacilitiesProblemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> FacilitiesProblem(Table<O> child, ForeignKey<O, FacilitiesProblemRecord> key) {
        super(child, key, FACILITIES_PROBLEM);
    }

    @Override
    public Schema getSchema() {
        return Webapp.WEBAPP;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FACILITIES_PROBLEM_PRIMARY, Indexes.FACILITIES_PROBLEM_PROBLEM_ID);
    }

    @Override
    public UniqueKey<FacilitiesProblemRecord> getPrimaryKey() {
        return Keys.KEY_FACILITIES_PROBLEM_PRIMARY;
    }

    @Override
    public List<UniqueKey<FacilitiesProblemRecord>> getKeys() {
        return Arrays.<UniqueKey<FacilitiesProblemRecord>>asList(Keys.KEY_FACILITIES_PROBLEM_PRIMARY);
    }

    @Override
    public List<ForeignKey<FacilitiesProblemRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FacilitiesProblemRecord, ?>>asList(Keys.FACILITIES_PROBLEM_IBFK_1, Keys.FACILITIES_PROBLEM_IBFK_2);
    }

    public Facilities facilities() {
        return new Facilities(this, Keys.FACILITIES_PROBLEM_IBFK_1);
    }

    public Problem problem() {
        return new Problem(this, Keys.FACILITIES_PROBLEM_IBFK_2);
    }

    @Override
    public FacilitiesProblem as(String alias) {
        return new FacilitiesProblem(DSL.name(alias), this);
    }

    @Override
    public FacilitiesProblem as(Name alias) {
        return new FacilitiesProblem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FacilitiesProblem rename(String name) {
        return new FacilitiesProblem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FacilitiesProblem rename(Name name) {
        return new FacilitiesProblem(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
