/*
 * This file is generated by jOOQ.
 */
package schema;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import schema.tables.Apartment;
import schema.tables.ApartmentRoom;
import schema.tables.Building;
import schema.tables.BuildingFloor;
import schema.tables.Facilities;
import schema.tables.FacilitiesProblem;
import schema.tables.Floor;
import schema.tables.FloorApartment;
import schema.tables.Problem;
import schema.tables.Room;
import schema.tables.RoomFacilities;
import schema.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webapp extends SchemaImpl {

    private static final long serialVersionUID = -908942462;

    /**
     * The reference instance of <code>webapp</code>
     */
    public static final Webapp WEBAPP = new Webapp();

    /**
     * The table <code>webapp.apartment</code>.
     */
    public final Apartment APARTMENT = schema.tables.Apartment.APARTMENT;

    /**
     * The table <code>webapp.apartment_room</code>.
     */
    public final ApartmentRoom APARTMENT_ROOM = schema.tables.ApartmentRoom.APARTMENT_ROOM;

    /**
     * The table <code>webapp.building</code>.
     */
    public final Building BUILDING = schema.tables.Building.BUILDING;

    /**
     * The table <code>webapp.building_floor</code>.
     */
    public final BuildingFloor BUILDING_FLOOR = schema.tables.BuildingFloor.BUILDING_FLOOR;

    /**
     * The table <code>webapp.facilities</code>.
     */
    public final Facilities FACILITIES = schema.tables.Facilities.FACILITIES;

    /**
     * The table <code>webapp.facilities_problem</code>.
     */
    public final FacilitiesProblem FACILITIES_PROBLEM = schema.tables.FacilitiesProblem.FACILITIES_PROBLEM;

    /**
     * The table <code>webapp.floor</code>.
     */
    public final Floor FLOOR = schema.tables.Floor.FLOOR;

    /**
     * The table <code>webapp.floor_apartment</code>.
     */
    public final FloorApartment FLOOR_APARTMENT = schema.tables.FloorApartment.FLOOR_APARTMENT;

    /**
     * The table <code>webapp.problem</code>.
     */
    public final Problem PROBLEM = schema.tables.Problem.PROBLEM;

    /**
     * The table <code>webapp.room</code>.
     */
    public final Room ROOM = schema.tables.Room.ROOM;

    /**
     * The table <code>webapp.room_facilities</code>.
     */
    public final RoomFacilities ROOM_FACILITIES = schema.tables.RoomFacilities.ROOM_FACILITIES;

    /**
     * The table <code>webapp.user</code>.
     */
    public final User USER = schema.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Webapp() {
        super("webapp", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Apartment.APARTMENT,
            ApartmentRoom.APARTMENT_ROOM,
            Building.BUILDING,
            BuildingFloor.BUILDING_FLOOR,
            Facilities.FACILITIES,
            FacilitiesProblem.FACILITIES_PROBLEM,
            Floor.FLOOR,
            FloorApartment.FLOOR_APARTMENT,
            Problem.PROBLEM,
            Room.ROOM,
            RoomFacilities.ROOM_FACILITIES,
            User.USER);
    }
}
