/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WebApp;

import helper.scheduler.ComplaintScheduler;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class AppTest {
    public static void main(String[] args) {
        ScheduledExecutorService scheduler;
        scheduler = Executors.newSingleThreadScheduledExecutor();
        scheduler.scheduleAtFixedRate(new ComplaintScheduler(), 0, 2, TimeUnit.MINUTES);

    }
}
