/*
 * This file is generated by jOOQ.
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.ApartmentRoom;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApartmentRoomRecord extends UpdatableRecordImpl<ApartmentRoomRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 2081864764;

    /**
     * Setter for <code>webapp.apartment_room.apartment_id</code>.
     */
    public void setApartmentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webapp.apartment_room.apartment_id</code>.
     */
    public Integer getApartmentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webapp.apartment_room.room_id</code>.
     */
    public void setRoomId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webapp.apartment_room.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ApartmentRoom.APARTMENT_ROOM.APARTMENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ApartmentRoom.APARTMENT_ROOM.ROOM_ID;
    }

    @Override
    public Integer component1() {
        return getApartmentId();
    }

    @Override
    public Integer component2() {
        return getRoomId();
    }

    @Override
    public Integer value1() {
        return getApartmentId();
    }

    @Override
    public Integer value2() {
        return getRoomId();
    }

    @Override
    public ApartmentRoomRecord value1(Integer value) {
        setApartmentId(value);
        return this;
    }

    @Override
    public ApartmentRoomRecord value2(Integer value) {
        setRoomId(value);
        return this;
    }

    @Override
    public ApartmentRoomRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApartmentRoomRecord
     */
    public ApartmentRoomRecord() {
        super(ApartmentRoom.APARTMENT_ROOM);
    }

    /**
     * Create a detached, initialised ApartmentRoomRecord
     */
    public ApartmentRoomRecord(Integer apartmentId, Integer roomId) {
        super(ApartmentRoom.APARTMENT_ROOM);

        set(0, apartmentId);
        set(1, roomId);
    }
}
