/*
 * This file is generated by jOOQ.
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.Apartment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApartmentRecord extends UpdatableRecordImpl<ApartmentRecord> implements Record5<Integer, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 11486366;

    /**
     * Setter for <code>webapp.apartment.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webapp.apartment.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webapp.apartment.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>webapp.apartment.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>webapp.apartment.code</code>.
     */
    public void setCode(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>webapp.apartment.code</code>.
     */
    public Integer getCode() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>webapp.apartment.building_id</code>.
     */
    public void setBuildingId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>webapp.apartment.building_id</code>.
     */
    public Integer getBuildingId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>webapp.apartment.floor_id</code>.
     */
    public void setFloorId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>webapp.apartment.floor_id</code>.
     */
    public Integer getFloorId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Apartment.APARTMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Apartment.APARTMENT.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Apartment.APARTMENT.CODE;
    }

    @Override
    public Field<Integer> field4() {
        return Apartment.APARTMENT.BUILDING_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Apartment.APARTMENT.FLOOR_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCode();
    }

    @Override
    public Integer component4() {
        return getBuildingId();
    }

    @Override
    public Integer component5() {
        return getFloorId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCode();
    }

    @Override
    public Integer value4() {
        return getBuildingId();
    }

    @Override
    public Integer value5() {
        return getFloorId();
    }

    @Override
    public ApartmentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ApartmentRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ApartmentRecord value3(Integer value) {
        setCode(value);
        return this;
    }

    @Override
    public ApartmentRecord value4(Integer value) {
        setBuildingId(value);
        return this;
    }

    @Override
    public ApartmentRecord value5(Integer value) {
        setFloorId(value);
        return this;
    }

    @Override
    public ApartmentRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApartmentRecord
     */
    public ApartmentRecord() {
        super(Apartment.APARTMENT);
    }

    /**
     * Create a detached, initialised ApartmentRecord
     */
    public ApartmentRecord(Integer id, String name, Integer code, Integer buildingId, Integer floorId) {
        super(Apartment.APARTMENT);

        set(0, id);
        set(1, name);
        set(2, code);
        set(3, buildingId);
        set(4, floorId);
    }
}
