/*
 * This file is generated by jOOQ.
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.BuildingFloor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BuildingFloorRecord extends UpdatableRecordImpl<BuildingFloorRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -749460280;

    /**
     * Setter for <code>webapp.building_floor.building_id</code>.
     */
    public void setBuildingId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webapp.building_floor.building_id</code>.
     */
    public Integer getBuildingId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webapp.building_floor.floor_id</code>.
     */
    public void setFloorId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webapp.building_floor.floor_id</code>.
     */
    public Integer getFloorId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BuildingFloor.BUILDING_FLOOR.BUILDING_ID;
    }

    @Override
    public Field<Integer> field2() {
        return BuildingFloor.BUILDING_FLOOR.FLOOR_ID;
    }

    @Override
    public Integer component1() {
        return getBuildingId();
    }

    @Override
    public Integer component2() {
        return getFloorId();
    }

    @Override
    public Integer value1() {
        return getBuildingId();
    }

    @Override
    public Integer value2() {
        return getFloorId();
    }

    @Override
    public BuildingFloorRecord value1(Integer value) {
        setBuildingId(value);
        return this;
    }

    @Override
    public BuildingFloorRecord value2(Integer value) {
        setFloorId(value);
        return this;
    }

    @Override
    public BuildingFloorRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BuildingFloorRecord
     */
    public BuildingFloorRecord() {
        super(BuildingFloor.BUILDING_FLOOR);
    }

    /**
     * Create a detached, initialised BuildingFloorRecord
     */
    public BuildingFloorRecord(Integer buildingId, Integer floorId) {
        super(BuildingFloor.BUILDING_FLOOR);

        set(0, buildingId);
        set(1, floorId);
    }
}
