/*
 * This file is generated by jOOQ.
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.Facilities;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FacilitiesRecord extends UpdatableRecordImpl<FacilitiesRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -25903076;

    /**
     * Setter for <code>webapp.facilities.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webapp.facilities.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webapp.facilities.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>webapp.facilities.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>webapp.facilities.facilities_type</code>.
     */
    public void setFacilitiesType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>webapp.facilities.facilities_type</code>.
     */
    public String getFacilitiesType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Facilities.FACILITIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Facilities.FACILITIES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Facilities.FACILITIES.FACILITIES_TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getFacilitiesType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getFacilitiesType();
    }

    @Override
    public FacilitiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FacilitiesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FacilitiesRecord value3(String value) {
        setFacilitiesType(value);
        return this;
    }

    @Override
    public FacilitiesRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FacilitiesRecord
     */
    public FacilitiesRecord() {
        super(Facilities.FACILITIES);
    }

    /**
     * Create a detached, initialised FacilitiesRecord
     */
    public FacilitiesRecord(Integer id, String name, String facilitiesType) {
        super(Facilities.FACILITIES);

        set(0, id);
        set(1, name);
        set(2, facilitiesType);
    }
}
