/*
 * This file is generated by jOOQ.
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.FloorApartment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FloorApartmentRecord extends UpdatableRecordImpl<FloorApartmentRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 945833624;

    /**
     * Setter for <code>webapp.floor_apartment.floor_id</code>.
     */
    public void setFloorId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webapp.floor_apartment.floor_id</code>.
     */
    public Integer getFloorId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webapp.floor_apartment.apartment_id</code>.
     */
    public void setApartmentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webapp.floor_apartment.apartment_id</code>.
     */
    public Integer getApartmentId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FloorApartment.FLOOR_APARTMENT.FLOOR_ID;
    }

    @Override
    public Field<Integer> field2() {
        return FloorApartment.FLOOR_APARTMENT.APARTMENT_ID;
    }

    @Override
    public Integer component1() {
        return getFloorId();
    }

    @Override
    public Integer component2() {
        return getApartmentId();
    }

    @Override
    public Integer value1() {
        return getFloorId();
    }

    @Override
    public Integer value2() {
        return getApartmentId();
    }

    @Override
    public FloorApartmentRecord value1(Integer value) {
        setFloorId(value);
        return this;
    }

    @Override
    public FloorApartmentRecord value2(Integer value) {
        setApartmentId(value);
        return this;
    }

    @Override
    public FloorApartmentRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FloorApartmentRecord
     */
    public FloorApartmentRecord() {
        super(FloorApartment.FLOOR_APARTMENT);
    }

    /**
     * Create a detached, initialised FloorApartmentRecord
     */
    public FloorApartmentRecord(Integer floorId, Integer apartmentId) {
        super(FloorApartment.FLOOR_APARTMENT);

        set(0, floorId);
        set(1, apartmentId);
    }
}
