/*
 * This file is generated by jOOQ.
 */
package schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import schema.tables.RoomFacilities;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomFacilitiesRecord extends UpdatableRecordImpl<RoomFacilitiesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1729853112;

    /**
     * Setter for <code>webapp.room_facilities.room_id</code>.
     */
    public void setRoomId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webapp.room_facilities.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webapp.room_facilities.facilities_id</code>.
     */
    public void setFacilitiesId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webapp.room_facilities.facilities_id</code>.
     */
    public Integer getFacilitiesId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RoomFacilities.ROOM_FACILITIES.ROOM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RoomFacilities.ROOM_FACILITIES.FACILITIES_ID;
    }

    @Override
    public Integer component1() {
        return getRoomId();
    }

    @Override
    public Integer component2() {
        return getFacilitiesId();
    }

    @Override
    public Integer value1() {
        return getRoomId();
    }

    @Override
    public Integer value2() {
        return getFacilitiesId();
    }

    @Override
    public RoomFacilitiesRecord value1(Integer value) {
        setRoomId(value);
        return this;
    }

    @Override
    public RoomFacilitiesRecord value2(Integer value) {
        setFacilitiesId(value);
        return this;
    }

    @Override
    public RoomFacilitiesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomFacilitiesRecord
     */
    public RoomFacilitiesRecord() {
        super(RoomFacilities.ROOM_FACILITIES);
    }

    /**
     * Create a detached, initialised RoomFacilitiesRecord
     */
    public RoomFacilitiesRecord(Integer roomId, Integer facilitiesId) {
        super(RoomFacilities.ROOM_FACILITIES);

        set(0, roomId);
        set(1, facilitiesId);
    }
}
